[[redirects]]
  from = "/api/watch/*"
  to = "https://test-v1-llytpr.vercel.app/api/watch/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/stream"
  to = "https://test-v1-llytpr.vercel.app/api/stream"
  status = 200
  force = true
